### ISSUE TITLE
The official addon fails to load on Linux

### ISSUE THREAD

**Issue by MiroslavR** [Panzerschrek/Chasm-Reverse#11]
The following assertion failure occurs:
```
PanzerChasm: ../PanzerChasm/model.cpp:499: void PanzerChasm::LoadModel_car(const FileContent&, PanzerChasm::Model&): Assertion `sounds_offset == model_file.size()' failed.
```
It seems to me that PanzerChasm failed to open "CARACTER/shot.car" but the game didn't error out straight away because VFS::ReadFile does not seem to distinguish between an empty and a non-existent file.

The actual filename is upper-case SHOT.CAR, which leads me to believe that the VFS doesn't work well with case-sensitive file systems (I am on Linux, BTW). A possible solution could be to recursively scan the addon directory and build an index allowing to search by normalized filenames.

**Comment by Panzerschrek** [comment]
Hi.
Here is a fix: https://github.com/Panzerschrek/Chasm-Reverse/commit/c63c3268a9296298d8aa42f601147ca9ff1bdd3e
Currently, a call to "ToUpper" should be enough, because all files in ADDON1 have upper-case names.
If you know addons, that break this rule, let me know.

**Comment by MiroslavR** [comment]
I'm afraid that's not enough, even if it makes the addon playable now. CHASM.INF seems to use lower-case filenames as well as backslashes. Putting a breakpoint at the end of Vfs::ReadFile reveals that these files fail to load:
- ANI/weapon\wf_bomb.ani
- ANI/weapon\wd_bomb.ani

**Comment by Panzerschrek** [comment]
Separators fixed:
https://github.com/Panzerschrek/Chasm-Reverse/commit/6a0a129186c43cfef0b75e2f839002b6a474df69

Now, all addon files must load correctly.

**Comment by MiroslavR** [comment]
Confirmed, thanks.
