### ISSUE TITLE
Can't pick up Reflectors and Chojin Masks

### ISSUE THREAD

**Issue by MiroslavR** [Panzerschrek/Chasm-Reverse#13]
Not a huge deal for the base game, but using a reflector is crucial to beating the last addon level.

**Comment by Panzerschrek** [comment]
Hi.
This items are not implemented yet.

**Comment by Panzerschrek** [comment]
Up.
Now, those items are implemented:
https://github.com/Panzerschrek/Chasm-Reverse/commit/403de7fdfe430d1f488c80a86e19185155c11ee4
https://github.com/Panzerschrek/Chasm-Reverse/commit/7111e03feac112763d62a1907efa8dd3004ee704

**Comment by MiroslavR** [comment]
Confirmed - the items work as expected. Bonifaciy still can't be killed with reflected projectiles, but I have included that issue in #14.
