### ISSUE TITLE
CMake build system

### ISSUE THREAD

**Issue by alexey-lysiuk** [Panzerschrek/Chasm-Reverse#21]
How about replacing qmake based build system with CMake one?

Pros:
- No need to install Qt for users of other IDEs (i.e. Visual Studio or Xcode) and desktop environments (other than KDE)
- Better support for dependency lookup, no more hard-coded SDL2 paths
- One project/solution for all targets (probably this is no longer an issue, I didn't use Qt for a while)
- QtCreator can still be used
- Travis CI and AppVeyor supports it out of the box

Both build systems can coexists if needed.

I will create CMake configuration file(s), just let me know if you are OK with it.

**Comment by Panzerschrek** [comment]
Hi. Good idea. I wanted to do it myself, but I did not have enough time for this.
You can add CMake files, but do not remove qmake files.
Also, do not forget about utilities.
