### ISSUE TITLE
Problem with in-game keyboard controls

### ISSUE THREAD

**Issue by alexey-lysiuk** [Panzerschrek/Chasm-Reverse#29]
In-game keyboard controls, i.e. move/look/jump, don't work when running without a configuration file.
User needs to enter Controls menu at least once in order to assign default buttons mapping automatically.

**Comment by Panzerschrek** [comment]
Fixed:
https://github.com/Panzerschrek/Chasm-Reverse/commit/59c674029949a0400f9bdb039000b8846a608198
