### ISSUE TITLE
Build fails on Linux

### ISSUE THREAD

**Issue by monreal** [Panzerschrek/Chasm-Reverse#4]
I try to build PanzerChasm on Linux and get the following:

09:54:37: Running steps for project PanzerChasm...
09:54:37: Starting: "/usr/bin/qmake-qt5" /home/micmon/Downloads/gaming/chasm/Chasm-Reverse-0.29.5/PanzerChasm/PanzerChasm.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
Info: creating stash file /home/micmon/Downloads/gaming/chasm/Chasm-Reverse-0.29.5/build-PanzerChasm-Desktop-Debug/.qmake.stash
WARNING: Failure to find: ../panzer_ogl_lib/polygon_buffer.cpp
WARNING: Failure to find: ../panzer_ogl_lib/shaders_loading.cpp
WARNING: Failure to find: ../panzer_ogl_lib/texture.cpp
WARNING: Failure to find: ../panzer_ogl_lib/framebuffer.cpp
WARNING: Failure to find: ../panzer_ogl_lib/func_addresses.cpp
WARNING: Failure to find: ../panzer_ogl_lib/glsl_program.cpp
WARNING: Failure to find: ../panzer_ogl_lib/matrix.cpp
WARNING: Failure to find: ../panzer_ogl_lib/ogl_state_manager.cpp
WARNING: Failure to find: ../panzer_ogl_lib/buffer_texture.cpp
09:54:37: The process "/usr/bin/qmake-qt5" exited normally.
09:54:37: Starting: "/usr/bin/make" qmake_all
make: Nothing to be done for 'qmake_all'.
09:54:37: The process "/usr/bin/make" exited normally.
09:54:37: Starting: "/usr/bin/make" 
g++ -c -pipe -mmmx -g -std=gnu++11 -Wall -W -fPIC -DDEBUG -DPC_MMX_INSTRUCTIONS -DQT_QML_DEBUG -I../PanzerChasm -I. -I../panzer_ogl_lib -isystem /usr/include/SDL2 -I/usr/lib64/qt5/mkspecs/linux-g++ -o client.o ../PanzerChasm/client/client.cpp
In file included from ../PanzerChasm/client/client.cpp:6:0:
../PanzerChasm/client/../math_utils.hpp:5:10: fatal error: vec.hpp: No such file or directory
 #include <vec.hpp>
          ^~~~~~~~~
compilation terminated.
make: *** [Makefile:680: client.o] Error 1
09:54:37: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project PanzerChasm (kit: Desktop)
The kit Desktop has configuration issues which might be the root cause for this problem.
When executing step "Make"
09:54:37: Elapsed time: 00:00.

Is building on Linux supported? The "panzer_ogl_lib" directory seems to be empty in both GIT and the release tarballs. Where is vec.hpp supposed to come from?

**Comment by TeslaRus** [comment]
math_utils.hpp:5:10: fatal error: vec.hpp: No such file or directory: something is wrong with path

**Comment by monreal** [comment]
I have a vec.hpp in /usr/include/boost/qvm/

**Comment by Panzerschrek** [comment]
Hi, @monreal!
Update git submodules, using this command: "git submodule update --init". This should fix your problem.

**Comment by monreal** [comment]
Thanks, I was able to compile after updating the submodule. Maybe this should go into the README?

**Comment by Panzerschrek** [comment]
This is second issue about same problem, so, maybe you're right.
