### ISSUE TITLE
Возможно ли написать программу на экспорт звуков из .car?

### ISSUE THREAD

**Issue by Nitestokeh** [Panzerschrek/Chasm-Reverse#47]
На данный момент это единственные файлы, которые никак нельзя распаковать или переконвертировать

**Comment by Panzerschrek** [comment]
В принципе возможно. Формат моделей и звуков в них [известен](https://github.com/Panzerschrek/Chasm-Reverse/blob/master/PanzerChasm/model.cpp#L40), PanzerChasm [читает](https://github.com/Panzerschrek/Chasm-Reverse/blob/master/PanzerChasm/model.cpp#L489) и [использует](https://github.com/Panzerschrek/Chasm-Reverse/blob/master/PanzerChasm/sound/sounds_loader.cpp#L52) звуки из моделей.
Думаю, если кому-то зачем-то нужно извлечь звуки отдельно, то он может достатчно быстро написать соотвествтующую утилиту.
