### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by Gr33nEyes** [Panzerschrek/Chasm-Reverse#50]
May I compile engine for Linux?

**Comment by Panzerschrek** [comment]
Compilation for GNU/Linux should work. It works for me, you just need to install any modern C++ compiler and SDL2 library.

**Comment by Panzerschrek** [comment]
Ubuntu build is now used in GithubActions, see https://github.com/Panzerschrek/Chasm-Reverse/blob/master/.github/workflows/cmake.yml#L18
