### ISSUE TITLE
Feature Request: BackportCpp submodule

### ISSUE THREAD

**Issue by jopadan** [Panzerschrek/Chasm-Reverse#61]
Add @bitwizeshift's [BackportCpp](https://github.com/bitwizeshift/BackportCpp) as a submodule to be able to use newer C++ versions features in C++ 11

**Comment by Panzerschrek** [comment]
I am not strongly against newer C++ version. It may be fine to use C++14 or even C++17.
But i think, that it's not worth it to update standard version for a couple of minor features. But it might be worth it, for example, if newer features, like std::variant, std::optional, std::filesystem, etc. will be used.

And it's is definitely not a good idea to use some thirdparty module for backporting features into older standard versions.

**Comment by jopadan** [comment]
Using C++17 seems to solve all the problems but introduces BeOS/Haiku and other operating systems using older gcc incompatibility.

**Comment by Panzerschrek** [comment]
I think BeOS/Haiku support is insignificant. Modern Windows (7+) and GNU/Linux (Ubuntu 18+) is enough.
